### ISSUE TITLE
bug: process.on("unhandledRejection") at bottom of index file

### ISSUE THREAD

**Issue by Miqhtiedev** [Lowie375/Gyromina#123]
The `process.on("unhandledRejection")` should be moved to the top of index.js. While it is unlikely, if something happens with the code executing prior to you creating that, the app would crash. 
https://github.com/Lowie375/Gyromina/blob/ceb7ba5586ad71cf1df66704d2d92b9d42369707/index.js#L227-L231

**Comment by Miqhtiedev** [comment]
I could PR this if you want

**Comment by Lowie375** [comment]
Acknowledged, will patch

**Comment by Lowie375** [comment]
Patch has been merged into `main` as of v1.2.9. Thanks for the help!
